import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header } from '@/components/header';

const nunito = localFont({
  src: '../public/fonts/Nunito.ttf',
  display: 'swap',
  variable: '--font-nunito'
});

const dmSans = localFont({
  src: '../public/fonts/DMSans.ttf',
  display: 'swap',
  variable: '--font-dm-sans'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${nunito.variable} ${dmSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
